<a href="https://colab.research.google.com/github/hauntedcupoftea/nikolaj/blob/main/Optimal_Routes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FINDING OPTIMAL ROUTES

In [ ]:
!pip install osmnx
!pip install networkx

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 95 kB 3.2 MB/s 
     |████████████████████████████████| 6.3 MB 28.2 MB/s 
     |████████████████████████████████| 11.2 MB 54.1 MB/s 
     |████████████████████████████████| 1.0 MB 55.1 MB/s 
     |████████████████████████████████| 62 kB 1.3 MB/s 
     |████████████████████████████████| 1.0 MB 59.4 MB/s 
     |████████████████████████████████| 16.7 MB 45.1 MB/s 
     |████████████████████████████████| 965 kB 46.7 MB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import osmnx as ox
import networkx as nx
ox.config(log_console=True, use_cache=True)
# define the start and end locations in latlng
start_latlng = (37.78497,-122.43327)
end_latlng = (37.78071,-122.41445)
# location where you want to find your route
place     = 'San Francisco, California, United States'
# find shortest route based on the mode of travel
mode      = 'walk'        # 'drive', 'bike', 'walk'
# find shortest path based on distance or time
optimizer = 'time'        # 'length','time'
# create graph from OSM within the boundaries of some 
# geocodable place(s)
graph = ox.graph_from_place(place, network_type = mode)
# find the nearest node to the start location
orig_node = ox.get_nearest_node(graph, start_latlng)
# find the nearest node to the end location
dest_node = ox.get_nearest_node(graph, end_latlng)
#  find the shortest path
shortest_route = nx.shortest_path(graph,
                                  orig_node,
                                  dest_node,
                                  weight=optimizer)

/usr/local/lib/python3.7/dist-packages/osmnx/distance.py:356: UserWarning: The `get_nearest_node` function has been deprecated and will be removed in a future release. Use the more efficient `distance.nearest_nodes` instead.
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/osmnx/distance.py:356: UserWarning: The `get_nearest_node` function has been deprecated and will be removed in a future release. Use the more efficient `distance.nearest_nodes` instead.
  warnings.warn(msg)


In [ ]:

shortest_route_map = ox.plot_route_folium(graph, shortest_route)
shortest_route_map

In [ ]:
import numpy as np
import pandas as pd
import csv
import datetime as dt
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/hauntedcupoftea/nikolaj/main/datasets/crimedata2016.csv')
df.head()

Date            Primary Type              Description  \
0  05/03/2016 11:40:00 PM                 BATTERY  DOMESTIC BATTERY SIMPLE   
1  05/03/2016 09:40:00 PM                 BATTERY  DOMESTIC BATTERY SIMPLE   
2  05/03/2016 11:31:00 PM  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT   
3  05/03/2016 10:10:00 PM                 BATTERY                   SIMPLE   
4  05/03/2016 10:00:00 PM                   THEFT           $500 AND UNDER   

  Location Description  Arrest  Domestic  Beat FBI Code  X Coordinate  \
0            APARTMENT    True      True  1022      08B     1154907.0   
1            RESIDENCE   False      True   313      08B     1183066.0   
2               STREET   False     False  1524       24     1140789.0   
3             SIDEWALK   False     False  1532      08B     1143223.0   
4            RESIDENCE   False      True  1523       06     1139890.0   

   Y Coordinate  Year                       Location   Latitude  Longitude  
0     1893681.0  2016  [41.864073157, -87.706818608]  41.864073 -87.706819  
1     1864330.0  2016   [41.782921527, -87.60436317]  41.782922 -87.604363  
2     1904819.0  2016  [41.894908283, -87.758371958]  41.894908 -87.758372  
3     1901475.0  2016  [41.885686845, -87.749515983]  41.885687 -87.749516  
4     1901675.0  2016  [41.886297242, -87.761750709]  41.886297 -87.761751

In [ ]:
timelist = []
for i in range(len(df)):
    datetime_object = dt.datetime.strptime(df['Date'][i][-11:], '%I:%M:%S %p')
    timelist.append(datetime_object)
df['Time'] = timelist
df.head()

Date            Primary Type              Description  \
0  05/03/2016 11:40:00 PM                 BATTERY  DOMESTIC BATTERY SIMPLE   
1  05/03/2016 09:40:00 PM                 BATTERY  DOMESTIC BATTERY SIMPLE   
2  05/03/2016 11:31:00 PM  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT   
3  05/03/2016 10:10:00 PM                 BATTERY                   SIMPLE   
4  05/03/2016 10:00:00 PM                   THEFT           $500 AND UNDER   

  Location Description  Arrest  Domestic  Beat FBI Code  X Coordinate  \
0            APARTMENT    True      True  1022      08B     1154907.0   
1            RESIDENCE   False      True   313      08B     1183066.0   
2               STREET   False     False  1524       24     1140789.0   
3             SIDEWALK   False     False  1532      08B     1143223.0   
4            RESIDENCE   False      True  1523       06     1139890.0   

   Y Coordinate  Year                       Location   Latitude  Longitude  \
0     1893681.0  2016  [41.864073157, -87.706818608]  41.864073 -87.706819   
1     1864330.0  2016   [41.782921527, -87.60436317]  41.782922 -87.604363   
2     1904819.0  2016  [41.894908283, -87.758371958]  41.894908 -87.758372   
3     1901475.0  2016  [41.885686845, -87.749515983]  41.885687 -87.749516   
4     1901675.0  2016  [41.886297242, -87.761750709]  41.886297 -87.761751   

                 Time  
0 1900-01-01 23:40:00  
1 1900-01-01 21:40:00  
2 1900-01-01 23:31:00  
3 1900-01-01 22:10:00  
4 1900-01-01 22:00:00

In [ ]:
cleandf = df.drop(['Date', 'X Coordinate', 'Y Coordinate', 'Beat', 'Year', 'FBI Code'], axis=1)
cleandf.head()

Primary Type              Description Location Description  \
0                 BATTERY  DOMESTIC BATTERY SIMPLE            APARTMENT   
1                 BATTERY  DOMESTIC BATTERY SIMPLE            RESIDENCE   
2  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT               STREET   
3                 BATTERY                   SIMPLE             SIDEWALK   
4                   THEFT           $500 AND UNDER            RESIDENCE   

   Arrest  Domestic                       Location   Latitude  Longitude  \
0    True      True  [41.864073157, -87.706818608]  41.864073 -87.706819   
1   False      True   [41.782921527, -87.60436317]  41.782922 -87.604363   
2   False     False  [41.894908283, -87.758371958]  41.894908 -87.758372   
3   False     False  [41.885686845, -87.749515983]  41.885687 -87.749516   
4   False      True  [41.886297242, -87.761750709]  41.886297 -87.761751   

                 Time  
0 1900-01-01 23:40:00  
1 1900-01-01 21:40:00  
2 1900-01-01 23:31:00  
3 1900-01-01 22:10:00  
4 1900-01-01 22:00:00

In [ ]:
# using sklearn's label encoder for more complex encoders where severity isn't needed
from sklearn import preprocessing as pp
lp = pp.LabelEncoder()
op = pp.OrdinalEncoder()
# creating a manual encoder for descriptions
basicCrime = list(set(cleandf['Primary Type']))
basicCrime

['MOTOR VEHICLE THEFT',
 'CRIMINAL TRESPASS',
 'PUBLIC PEACE VIOLATION',
 'NON - CRIMINAL',
 'BURGLARY',
 'GAMBLING',
 'THEFT',
 'LIQUOR LAW VIOLATION',
 'HUMAN TRAFFICKING',
 'OBSCENITY',
 'INTIMIDATION',
 'NON-CRIMINAL',
 'INTERFERENCE WITH PUBLIC OFFICER',
 'DECEPTIVE PRACTICE',
 'CRIMINAL DAMAGE',
 'BATTERY',
 'OTHER NARCOTIC VIOLATION',
 'CONCEALED CARRY LICENSE VIOLATION',
 'KIDNAPPING',
 'OTHER OFFENSE',
 'ARSON',
 'ASSAULT',
 'PROSTITUTION',
 'CRIM SEXUAL ASSAULT',
 'NARCOTICS',
 'NON-CRIMINAL (SUBJECT SPECIFIED)',
 'OFFENSE INVOLVING CHILDREN',
 'PUBLIC INDECENCY',
 'SEX OFFENSE',
 'HOMICIDE',
 'STALKING',
 'WEAPONS VIOLATION',
 'ROBBERY']

In [ ]:
# manual encoding of crimes based on severity
# in order to generate a heatmap of which areas are the most dangerous
primList = {'NON - CRIMINAL': 0, 'NON-CRIMINAL (SUBJECT SPECIFIED)': 0, 'NON-CRIMINAL': 0,
            'INTIMIDATION': 1, 'OBSCENITY': 1, 'OTHER OFFENSE': 1, 'PUBLIC INDECENCY': 1,
            'LIQUOR LAW VIOLATION': 2, 'PUBLIC PEACE VIOLATION': 2, 'CONCEALED CARRY LICENSE VIOLATION': 2,
            'PROSTITUTION': 3, 'GAMBLING': 3, 'INTERFERENCE WITH PUBLIC OFFICER': 3, 'STALKING': 3,
            'ARSON': 6, 'BURGLARY': 5, 'BATTERY': 2, 'ROBBERY': 5, 'SEX OFFENSE': 5, 'ASSAULT': 3,
            'THEFT': 4, 'DECEPTIVE PRACTICE': 5, 'CRIMINAL TRESPASS': 4, 'CRIMINAL DAMAGE': 4, 'WEAPONS VIOLATION' : 5,
            'MOTOR VEHICLE THEFT': 5, 'OFFENSE INVOLVING CHILDREN': 5, 'KIDNAPPING': 5, 'NARCOTICS': 5,
            'OTHER NARCOTIC VIOLATION' : 4,'HUMAN TRAFFICKING' : 6,'CRIM SEXUAL ASSAULT' : 6, 'HOMICIDE' : 6}
len(primList)

33

In [ ]:
# running the encode, along with the other encoders and adding them all to the dataframe
encodePrim = [primList[i] for i in cleandf['Primary Type']]
cleandf['desc'] = lp.fit_transform(cleandf['Description'])
cleandf['locdesc'] = lp.fit_transform(cleandf['Location Description'])
cleandf['type'] = encodePrim
cleandf.head()

Primary Type              Description Location Description  \
0                 BATTERY  DOMESTIC BATTERY SIMPLE            APARTMENT   
1                 BATTERY  DOMESTIC BATTERY SIMPLE            RESIDENCE   
2  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT               STREET   
3                 BATTERY                   SIMPLE             SIDEWALK   
4                   THEFT           $500 AND UNDER            RESIDENCE   

   Arrest  Domestic                       Location   Latitude  Longitude  \
0    True      True  [41.864073157, -87.706818608]  41.864073 -87.706819   
1   False      True   [41.782921527, -87.60436317]  41.782922 -87.604363   
2   False     False  [41.894908283, -87.758371958]  41.894908 -87.758372   
3   False     False  [41.885686845, -87.749515983]  41.885687 -87.749516   
4   False      True  [41.886297242, -87.761750709]  41.886297 -87.761751   

                 Time  desc  locdesc  type  
0 1900-01-01 23:40:00   104       17     2  
1 1900-01-01 21:40:00   104       99     2  
2 1900-01-01 23:31:00   234      114     2  
3 1900-01-01 22:10:00   251      111     2  
4 1900-01-01 22:00:00     0       99     4

In [ ]:
from collections import Counter
count = Counter(cleandf['Location'])
print(count)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
colormap = {0 : '#0d0887', 1 : '#5d02a4', 2 : '#9b169e', 3 : '#c94579', 
            4 : '#ed7953', 5 : '#fcb331', 6 : '#f0f821'}
plt.scatter(cleandf['Longitude'], cleandf['Latitude'], marker='.', 
            c=[colormap[i] for i in cleandf['type']])
plt.show()

ImportError: ignored

<Figure size 432x288 with 1 Axes>

In [ ]:
# making a time filter
def timeFilter(start: str, end: str) -> pd.DataFrame:
    start = dt.datetime.strptime(start, '%H:%M:%S')
    end = dt.datetime.strptime(end, '%H:%M:%S')
    if (start < end):
        return cleandf.loc[(df['Time'] >= start) & (df['Time'] < end)]
    else:
        return cleandf.loc[(df['Time'] >= start) | (df['Time'] < end)]

# examplse of if
ifs = timeFilter('17:00:00', '09:00:00')
# example of else
els = timeFilter('09:00:00','17:00:00')
# check to see if we cover everything
print(len(ifs) + len(els) == len(cleandf))
els.shape

True


(98481, 12)

In [ ]:
cleandf.head()

Primary Type              Description Location Description  \
0                 BATTERY  DOMESTIC BATTERY SIMPLE            APARTMENT   
1                 BATTERY  DOMESTIC BATTERY SIMPLE            RESIDENCE   
2  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT               STREET   
3                 BATTERY                   SIMPLE             SIDEWALK   
4                   THEFT           $500 AND UNDER            RESIDENCE   

   Arrest  Domestic                       Location   Latitude  Longitude  \
0    True      True  [41.864073157, -87.706818608]  41.864073 -87.706819   
1   False      True   [41.782921527, -87.60436317]  41.782922 -87.604363   
2   False     False  [41.894908283, -87.758371958]  41.894908 -87.758372   
3   False     False  [41.885686845, -87.749515983]  41.885687 -87.749516   
4   False      True  [41.886297242, -87.761750709]  41.886297 -87.761751   

                 Time  desc  locdesc  type  
0 1900-01-01 23:40:00   104       17     2  
1 1900-01-01 21:40:00   104       99     2  
2 1900-01-01 23:31:00   234      114     2  
3 1900-01-01 22:10:00   251      111     2  
4 1900-01-01 22:00:00     0       99     4

In [ ]:
from sklearn.cluster import *
def one():
    nCluster = int(input())
#    color = list(np.random.choice(range(256), size=nCluster))
    model = KMeans(n_clusters=nCluster)
    results = model.fit_predict(cleandf.loc(axis=1)['Latitude':'Longitude'])
#    plt.scatter(cleandf['Longitude'], cleandf['Latitude'], marker='.', 
#                c=[color[i] for i in results])
    return results

In [ ]:
results = one()
color = list(np.random.choice(range(256), size=len(set(results))))
cleandf['cluster'] = results

5


In [ ]:
from scipy.spatial import Delaunay
def alpha_shape(points, alpha, only_outer=True):
    assert points.shape[0] > 3, "Need at least four points"
    def add_edge(edges, i, j):
        if (i, j) in edges or (j, i) in edges:
            assert (j, i) in edges, "Can't go twice over same directed edge right?"
            if only_outer:
                edges.remove((j, i))
            return
        edges.add((i, j))
    tri = Delaunay(points)
    edges = set()
    for ia, ib, ic in tri.vertices:
        pa = points[ia]
        pb = points[ib]
        pc = points[ic]
        a = np.sqrt((pa[0] - pb[0]) ** 2 + (pa[1] - pb[1]) ** 2)
        b = np.sqrt((pb[0] - pc[0]) ** 2 + (pb[1] - pc[1]) ** 2)
        c = np.sqrt((pc[0] - pa[0]) ** 2 + (pc[1] - pa[1]) ** 2)
        s = (a + b + c) / 2.0
        area = np.sqrt(s * (s - a) * (s - b) * (s - c))
        circum_r = a * b * c / (4.0 * area)
        if circum_r < alpha:
            add_edge(edges, ia, ib)
            add_edge(edges, ib, ic)
            add_edge(edges, ic, ia)
    return edges

In [ ]:
import warnings
warnings.filterwarnings("ignore")
# Plotting the output
fig, ax = plt.subplots(figsize=(30, 8))
for i in range(len(set(results))):
    fildf = cleandf[cleandf['cluster'] == i]
    nmod = KMeans(int(np.power(len(fildf), 0.25)))
    nmod.fit([[i, j] for i, j in zip(fildf['Longitude'], fildf['Latitude'])])
    centers = nmod.cluster_centers_
    points = np.array([[i, j] for i, j in zip(fildf['Longitude'], fildf['Latitude'])])
    try:
        edges = alpha_shape(centers, alpha=4, only_outer=True)
    except:
        continue
    plt.subplot(1, 3, 1)
    plt.plot(points[:, 0], points[:, 1], '.')
    # USE EDGES AND CENTERS TO PLOT NORMAL ROUTES, REMOVE POINTS AND ALL REFERENCES IN FINAL CODE
    for i, j in edges:
        plt.plot(centers[[i, j], 0], centers[[i, j], 1])
plt.show()

ImportError: ignored

<Figure size 2160x576 with 1 Axes>

In [ ]:
print(edges)

{(7, 12), (8, 0), (3, 7), (5, 3), (0, 9), (9, 5), (12, 8)}


In [ ]:
print(centers)

[[-87.68951195  41.92495812]
 [-87.68351385  41.96548057]
 [-87.65688301  41.96610592]
 [-87.67140046  42.01352402]
 [-87.71084857  41.96334197]
 [-87.66328871  41.99001439]
 [-87.66931734  41.93354697]
 [-87.75343238  41.99065928]
 [-87.70791866  41.94091957]
 [-87.64991639  41.94162094]
 [-87.70417905  41.98684684]
 [-87.69096144  42.00290885]
 [-87.73002838  41.96504727]]


In [ ]:
centers[1]

array([-87.68351385,  41.96548057])

In [ ]:
centers[0]

array([-87.68951195,  41.92495812])

In [ ]:
# ox.config(log_console=True, use_cache=True)
# # define the start and end locations in latlng
# # start_latlng = (37.78497,-122.43327)
# # end_latlng = (37.78071,-122.41445)

# start_latlang = centers[0]
# end_latlng = centers[2]
# # location where you want to find your route
# place     = 'Chicago, Illinois, United States'
# # find shortest route based on the mode of travel
# mode      = 'drive'        # 'drive', 'bike', 'walk'
# # find shortest path based on distance or time
# optimizer = 'time'        # 'length','time'
# # create graph from OSM within the boundaries of some 
# # geocodable place(s)
# graph = ox.graph_from_place(place, network_type = mode)
# # find the nearest node to the start location
# orig_node = ox.get_nearest_node(graph, start_latlng)
# # find the nearest node to the end location
# dest_node = ox.get_nearest_node(graph, end_latlng)
# #  find the shortest path
# shortest_route = nx.shortest_path(graph,
#                                   orig_node,
#                                   dest_node,
#                                   weight=optimizer)

KeyboardInterrupt: ignored

In [ ]:

# shortest_route_map = ox.plot_route_folium(graph, shortest_route)
# shortest_route_map

In [ ]:
def find_route(st,end):
  ox.config(log_console=True, use_cache=True)
  # define the start and end locations in latlng
  # start_latlng = (37.78497,-122.43327)
  # end_latlng = (37.78071,-122.41445)

  start_latlang = st
  end_latlng = end
  # location where you want to find your route
  place     = 'Chicago, Illinois, United States'
  # find shortest route based on the mode of travel
  mode      = 'drive'        # 'drive', 'bike', 'walk'
  # find shortest path based on distance or time
  optimizer = 'time'        # 'length','time'
  # create graph from OSM within the boundaries of some 
  # geocodable place(s)
  graph = ox.graph_from_place(place, network_type = mode)
  # find the nearest node to the start location
  orig_node = ox.get_nearest_node(graph, start_latlng)
  # find the nearest node to the end location
  dest_node = ox.get_nearest_node(graph, end_latlng)
  #  find the shortest path
  shortest_route = nx.shortest_path(graph,
                                    orig_node,
                                    dest_node,
                                    weight=optimizer)
 
  shortest_route_map = ox.plot_route_folium(graph, shortest_route)
  return shortest_route_map
find_route(centers[12],centers[3])

In [ ]:
# !pip install gmplot

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 164 kB 5.1 MB/s 


In [ ]:
# import gmplot  
# latitudeList = [ 28.691234, 28.818390, 29.089301 ]  
# longitudeList = [ 77.193802, 77.023890, 76.865211 ]  
# myGmap = gmplot.GoogleMapPlotter(28.612894, 77.229446, 11)  
# myGmap.scatter( latitudeList, longitudeList, '#FF0000', size = 40, marker = False )  
# # drawing a polygon using the polygon() method  
# # of the GoogleMapPlotter class with the help of coordinates  
# myGmap.polygon( latitudeList, longitudeList, color = 'cornflowerblue' )  


None


In [ ]:
centers[0]

array([-87.68951195,  41.92495812])

In [ ]:
centers[1]

array([-87.68351385,  41.96548057])

In [ ]:
centers[2]

array([-87.65688301,  41.96610592])